name: recycling_app
description: "ARAMVA Recycle"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1  # ADD THIS LINE

flutter_icons:  # ADD THIS ENTIRE SECTION
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0F0F0F"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/